### DISCUSSION TITLE
Beyond Services: Using Docker Compose as a Task Runner

### DISCUSSION THREAD

**Discussion by dudo** [gitops-ci-cd/discussions#1] [Blog]
When most people think of Docker Compose[^1], they picture multi-container orchestration–spinning up a web app, database, and message broker, all working in harmony. But Docker Compose can handle more than just services. It can also serve as a task runner, encapsulating your project's development workflows in a single, portable file.

In my own work, Docker Compose goes beyond just orchestrating services. It's also the backbone for tasks like linting, testing, database migrations, and even running local CLI commands (npm, go, protoc, and more). I've found this to be a powerful pattern–and here's why you might want to consider it.

## The Case for Docker Compose as a Task Runner

Development teams juggle a variety of tools and scripts to handle repetitive tasks such as installing dependencies, linting, testing, and running database migrations. Typically, you might see:

- Custom shell scripts
- Language-specific task runners (e.g., npm scripts, Makefiles, Taskfiles)
- Manually installed dependencies on individual machines (e.g., apt, brew, chocolatey)
- Version managers (e.g., nvm, pyenv, goenv)

While these approaches can work, they often lead to inconsistency across environments. One developer might have a different version of Node or Go installed, or might forget to install a particular CLI. Docker Compose solves this by bundling all task dependencies into containers, ensuring every developer runs tasks in identical environments.

The goal is to run all commands used for local development as `docker compose run --rm` commands (which can/should be conveniently aliased as `dr`). A bonus feature of this tooling is that trailing "arguments" are simply passed to the command, unlike make, for instance, which requires env to be set. This is especially useful for common language commands, e.g.:

```sh
# go
dr go get github.com/gorilla/mux
dr go mod tidy

# js
dr npm install left-pad --save
dr npm update
dr npx mocha

# ruby
dr bundle add pundit 
dr bundle update
dr bundle exec rake db:test:init

# python
dr pip install -r /path/to/requirements.txt

# you get the drift...
```

It's business as usual, with a leading `dr`...

![doctor](https://github.com/user-attachments/assets/597b68a3-f9ff-49dd-9c14-24347a2ae024)

## Version Management with Docker Simplifies Development

Managing language versions and dependencies across different developer environments can be a frustrating and error-prone process. Tools like `nvm`, `pyenv`, or `goenv` are helpful, but they require careful setup, regular updates, and can lead to inconsistencies—especially when team members forget to switch to the right version.

Docker eliminates these headaches by acting as the ultimate version manager. By specifying the exact versions of your tools and languages in your Dockerfile (e.g., `FROM golang:1.23`, `FROM node:22`), Docker ensures everyone works in identical environments. No more “it works on my machine” scenarios or wasting time debugging version mismatches.

With Docker, you don’t need to install Node.js, Python, or Go locally. Instead, all versioning is handled within the container, ensuring consistency across local development, CI/CD pipelines, and production. This means less time managing tools and more time building great software. Plus, when it’s time to upgrade, the process is as simple as editing a line in your Dockerfile.

## How It Works

Let's explore how you can structure your compose.yaml files to include both core services and CLI tooling. Below are two scenarios: a Go microservice and a Node.js application.

### Go Example

Provided you have a Go project with a `Dockerfile` as follows:

```Dockerfile
# This stage only downloads and caches Go modules.
FROM golang:1.23 AS base

WORKDIR /usr/src/app

# Copy the Go Modules manifests first, then download dependencies.
COPY go.* ./
RUN go mod download

# If you have vendoring:
# RUN go mod vendor

# Now copy the rest of the source code.
COPY . ./

ENTRYPOINT [ "go" ]

# This stage compiles the binary.
FROM base AS builder

WORKDIR /usr/src/app

# Create a non-root user and group to run the application.
RUN groupadd -r nonroot && useradd --no-log-init -r -g nonroot nonroot

# Compile the binary. If the code has compilation issues,
# you can comment out or skip this step.
RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -a -installsuffix cgo -o /go/bin/main ./cmd/server/main.go

# Use a minimal scratch image for the final container.
FROM scratch

WORKDIR /usr/src/app

# Import user and group info
COPY --from=builder /etc/passwd /etc/group /etc/

# Import CA certificates (if your app makes HTTPS calls).
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Copy the compiled binary from the builder stage.
COPY --from=builder /go/bin/main ./

# Use the nonroot user to run the application
USER nonroot:nonroot

EXPOSE 50051

# Define the entrypoint for the Docker image.
ENTRYPOINT ["/usr/src/app/main"]
```

you can set up a `compose.yaml` file like this:

```yaml
services:
  go: &go
    env_file:
      - path: .env
        required: false
    tty: true
    stdin_open: true
    build:
      context: .
      target: base
    entrypoint: go
    command: help
    volumes:
      - .:/usr/src/app:delegated # Bind mount the source code
      - gomod:/go/pkg/mod:cached # Volume mount Go modules
      - ${LOCAL_DEP_PATH:-..}:/local # Provide a local path for dependency injection

  # We can't use <<: *go with develop.watch due to the volume overlap.
  app:
    env_file: .env
    tty: true
    stdin_open: true
    build:
      context: .
      target: builder
    entrypoint: go
    command: run ./cmd/server/main.go
    ports:
      - ${PORT:-50051}:${PORT:-50051}
    develop:
      watch:
        - action: sync+restart
          path: ./cmd/
          target: /usr/src/app/cmd/
        - action: sync+restart
          path: ./internal/
          target: /usr/src/app/internal/
        - action: sync+restart
          path: ./go.mod
          target: /usr/src/app/go.mod
        - action: sync+restart
          path: ./go.sum
          target: /usr/src/app/go.sum
    volumes:
      - gomod:/go/pkg/mod:cached
    depends_on:
      - install
      - postgres

  postgres:
    env_file:
      - path: .env
        required: false
    image: postgres:17
    user: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  install:
    <<: *go
     profiles: ["task"]
    command: mod tidy

  lint:
    <<: *go
    profiles: ["task"]
    command: vet ./...

  test:
    <<: *go
    profiles: ["task"]
    command: test ./...

  db.migrate:
    <<: *go
    profiles: ["task"]
    entrypoint: go run github.com/jackc/tern
    command: migrate

volumes:
  gomod: {}
  postgres: {}
```

The go service defines a baseline environment using a specific version of the official Go image, per the Dockerfile. Other tasks (e.g., lint, test, db.migrate) inherit from go via YAML anchors, which keeps your configuration DRY ("Don't Repeat Yourself"). We provide a `profiles`[^2] key to avoid running "tasks" when we call `docker compose watch`[^3] or `docker compose up`.

### Node.js Example

For a Node.js project, you can use a similar approach. Given the following `Dockerfile`:

```Dockerfile
# Start from the official LTS Node image. No need for version managers on the host machine.
FROM node:24 AS base

WORKDIR /usr/src/app

# Copy the package files and download the dependencies.
# This is done before installing dependencies or copying code to leverage Docker cache layers.
COPY package*.json ./

# Now copy the rest of the source code.
COPY . ./

# Update npm to the latest version.
RUN npm install -g npm@latest

ENTRYPOINT [ "npm" ]

# Continue to create a build artifact.
FROM base

WORKDIR /usr/src/app

# Install only production dependencies from the lock file.
RUN npm ci --silent --production

EXPOSE 8080

# This is the command that will be run when the container starts.
ENTRYPOINT [ "npm" ]
CMD [ "src/index.js" ]
```

we can define a `compose.yaml` file like this:

```yaml
services:
  npm: &npm
    env_file:
      - path: .env
        required: false
    tty: true
    stdin_open: true
    build:
      context: .
      target: base
    entrypoint: npm
    command: help
    volumes:
      - .:/usr/src/app:delegated # Bind mount the source code
      - node_modules:/node_modules:cached # Volume mount Node modules

  npx: &npx
    <<: *npm
    entrypoint: npx
    command: -h

  # We can't use <<: *npm with develop.watch due to the volume overlap.
  app:
    env_file:
      - path: .env
        required: false
    tty: true
    stdin_open: true
    build:
      context: .
      target: base
    entrypoint: npm
    command: run start
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    develop:
      watch:
        - action: sync+restart
          path: ./src/
          target: /usr/src/app/src/
        - action: sync+restart
          path: ./package.json
          target: /usr/src/app/package.json
        - action: sync+restart
          path: ./package-lock.json
          target: /usr/src/app/package-lock.json
    volumes:
      - node_modules:/node_modules:cached
    depends_on:
      - install

  install:
    <<: *npm
    profiles: ["task"]
    command: install --include=dev

  lint:
    <<: *npm
    profiles: ["task"]
    command: eslint

  test:
    <<: *npm
    profiles: ["task"]
    command: mocha

volumes:
  node_modules: {}
```

Similarly, the `npm` service handles Node.js tasks. Other tasks like install, lint, and test inherit from it to share the same container environment. This works just as well for client side applications, defining tasks for tailwindcss, webpack, or any other tooling you might use–You just wouldn't need the multi-stage build in the Dockerfile for front-end projects.

## Why This Pattern Works

- **Consistency**

    Every developer uses the same container-based setup[^4], eliminating "works on my machine" issues.

- **Portability**

    Whether on macOS, Windows, or Linux, the environment stays consistent.

- **Simplicity**

    All task definitions live in a single Compose file, reducing the mental load of remembering custom scripts.

- **Modularity**

    YAML anchors (<<:) keep the file DRY and easy to maintain.

## Alternatives and Trade-Offs

While this method has advantages, it does come with trade-offs:

- **Compose File Complexity**

    Adding too many tasks can clutter your compose.yaml. Consider splitting tasks into multiple files, or layering Compose configs.

- **Unconventional Usage**

    Some developers are used to Docker Compose purely for microservices. You may need to explain and document this approach for your team, or reference this article!

- **Existing Tools**

    Makefiles, Taskfiles, scripts, or dedicated task runners are lightweight alternatives, but have the *drawback* that they are dependent upon installation of environment-specific tooling, which can lead to inconsistent behavior between development machines.

## Why You Should Try It

If you've ever battled inconsistent local setups or wasted time installing multiple tools, this strategy can simplify your workflow. With Docker Compose as a task runner, you create a single source of truth for all your development tasks, making onboarding new contributors faster and more seamless.

In a world where both consistency and speed matter, why limit Docker Compose to just services? Embrace its flexibility to unify your entire development process.

Do you find this approach interesting? Would you give it a shot in your own projects? Share your thoughts!

[^1]: <https://docs.docker.com/compose/>
[^2]: <https://docs.docker.com/reference/compose-file/profiles/>
[^3]: <https://docs.docker.com/compose/how-tos/file-watch/>
[^4]: <https://12factor.net/dev-prod-parity>
